
name: ClusterDev Plan for my-project

on:
  push:
    branches:
      - 'cluster.dev-*'
  pull_request:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run ClusterDev Plan
      run: |
        cd .cluster.dev/my-project
        docker run --rm -v $(pwd):/workspace/cluster-dev clusterdev/cluster.dev:v0.7.18 plan
    